### ISSUE TITLE
buildlog for nrf5340 rev2?

### ISSUE THREAD

**Issue by onriv** [dilshod/36-choc-key-ortholinear-split#4]
Hi thanks for the awesome design!

Is the build log and parts list for nrf5340 rev2 still same as the main branch? I saw some pictures in 
https://www.reddit.com/r/ErgoMechKeyboards/comments/1g5knxl/36key_ortholinear_split_keyboard_second_version/ and it seems requiring some more resistor and chips etc.

**Comment by dilshod** [comment]
It is different, you can find all the components in the schematic file.

**Comment by onriv** [comment]
> It is different, you can find all the components in the schematic file.

Got it! Thanks for the kindly help!
